#!/usr/bin/env node
// Local / CI database test harness (pgTAP via the Supabase CLI + Docker).
//
// Why a separate workdir: the full history in supabase/migrations/ cannot be
// replayed on a fresh database — pre-August files depend on objects that were
// only ever created live (see CLAUDE.md "Known issue — git/DB drift"). The
// 13/08 baseline (20260813999999_baseline_reconcile_with_live.sql) is a
// complete introspected snapshot of the live schema, so a fresh test DB is
// built from the baseline plus every migration after it. The repo's
// migration history is left untouched.
//
// This never talks to the hosted project: the generated config uses its own
// project id, and only local Docker containers are started.
//
// Usage:
//   node scripts/db-test.mjs start   # build .dbtest/ and start a fresh local stack
//   node scripts/db-test.mjs test    # (re)sync tests and run pgTAP
//   node scripts/db-test.mjs reset   # rebuild the DB from migrations (fresh state)
//   node scripts/db-test.mjs stop    # stop and discard the local stack

import { appendFileSync, cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = process.cwd();
const SRC_MIGRATIONS = path.join(ROOT, "supabase", "migrations");
const SRC_TESTS = path.join(ROOT, "supabase", "tests");
const REFERENCE_DATA = path.join(ROOT, "supabase", "test-fixtures", "reference_data.sql");
const TEST_HELPERS = path.join(ROOT, "supabase", "test-fixtures", "test_helpers.sql");
const WORKDIR = path.join(ROOT, ".dbtest");
const WD_SUPABASE = path.join(WORKDIR, "supabase");
const BASELINE = "20260813999999";
const PROJECT_ID = "conz-dbtest";

// Services pgTAP does not need (keeps memory use low on laptops and CI).
const EXCLUDE = [
  "studio", "imgproxy", "vector", "logflare", "edge-runtime",
  "supavisor", "realtime", "mailpit", "postgres-meta",
].join(",");

function build() {
  rmSync(path.join(WD_SUPABASE, "migrations"), { recursive: true, force: true });
  mkdirSync(path.join(WD_SUPABASE, "migrations"), { recursive: true });
  writeFileSync(
    path.join(WD_SUPABASE, "config.toml"),
    `# GENERATED by scripts/db-test.mjs — local test stack only, never linked.\n` +
      `project_id = "${PROJECT_ID}"\n\n[db]\nmajor_version = 17\n`,
  );
  const files = readdirSync(SRC_MIGRATIONS)
    .filter((f) => /^\d{14}_.+\.sql$/.test(f) && f.slice(0, 14) >= BASELINE)
    .sort();
  for (const f of files) {
    cpSync(path.join(SRC_MIGRATIONS, f), path.join(WD_SUPABASE, "migrations", f));
  }
  // The baseline is schema-only; later migrations assume configuration rows
  // (material prices, platform settings) exist. Append them to the copy.
  const baselineCopy = path.join(WD_SUPABASE, "migrations", files[0]);
  appendFileSync(baselineCopy, "\n\n" + readFileSync(REFERENCE_DATA, "utf8"));
  // Test helpers (pgTAP, identity switching, fixtures) go last.
  cpSync(TEST_HELPERS, path.join(WD_SUPABASE, "migrations", "29991231235959_test_helpers.sql"));
  syncTests();
  console.log(`db-test: ${files.length} migrations from ${files[0]} to ${files.at(-1)}`);
}

function syncTests() {
  rmSync(path.join(WD_SUPABASE, "tests"), { recursive: true, force: true });
  if (existsSync(SRC_TESTS)) cpSync(SRC_TESTS, path.join(WD_SUPABASE, "tests"), { recursive: true });
}

function supabase(args) {
  const r = spawnSync("npx", ["supabase", ...args, "--workdir", WORKDIR], {
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (r.status !== 0) process.exit(r.status ?? 1);
}

const cmd = process.argv[2];
switch (cmd) {
  case "start":
    build();
    supabase(["start", "-x", EXCLUDE]);
    break;
  case "reset":
    build();
    supabase(["db", "reset", "--local"]);
    break;
  case "test":
    syncTests();
    supabase(["test", "db", "--local"]);
    break;
  case "stop":
    supabase(["stop", "--no-backup"]);
    break;
  default:
    console.error("usage: node scripts/db-test.mjs start|test|reset|stop");
    process.exit(2);
}
